### ISSUE TITLE
Support older EZ3 plans 

### ISSUE THREAD

**Issue by MicahRam** [cheald/srp-bill-calculator#4]
SRP used to have an option to pick the staring time for peek hours on the EZ3 plan 2, 3 or 4 PM. The 2 and 4 PM plans are no longer offered but they have not forced customers off of them yet. 

Although they are no longer offered its nice to know the amount for comparison when considering switching off of them.

**Comment by cheald** [comment]
Oh, interesting. I'll add a switch like `--srp-ez3-start-hour` which would take one of (14, 15, 16), defaulting to 15.

**Comment by cheald** [comment]
Just pushed 4166523403c0a92590a95f770a785ad47e124571 which provides this feature. You can specify `--srp-ez3-start-hour 14/15/16` to select the start of the EZ3 period applicable to your plan.
