### ISSUE TITLE
EV plan has incorrect peak hour calculation

### ISSUE THREAD

**Issue by BlakeHepner** [cheald/srp-bill-calculator#6]
In the srp/ev.rb and ev_solar.rb files, the weekend check only ever occurs during the winter. In the summer months, weekend days have peak rate charges being applied, throwing the numbers off.

in ev.rb, it occurs on line 26, but I would also expect it to occur on 35.

I reordered it a bit to this which pulls the weekend and super off peak checking to top level, which seems to fix everything:

      def level(date)
        return :off_peak if holiday?(date)
        case date.hour
        when 0...5, 23..24
            :super_off_peak
        else
          case date.wday  
          when 0, 6
          :off_peak
          else
            case season(date)
            when :winter
              case date.hour
              when 5...9, 17...21
                :on_peak
              else
              :off_peak
              end
            else
              case date.hour
              when 14...20
                :on_peak
              else
                :off_peak
              end
            end
          end
        end
      end

**Comment by cheald** [comment]
Great catch! I'll get that merged in.

**Comment by cheald** [comment]
Fixed in 9eee229. Thanks!
